# SPDX-License-Identifier: copyleft-next-0.3.1
#
# kdevops plugin: knlp
#
# This file is included when the knlp plugin is installed.

KNLP_PLUGIN_DIR := $(HOME)/.config/kdevops/plugins/knlp

ifeq (y,$(CONFIG_KDEVOPS_USER_WORKFLOW_KNLP))
include $(KNLP_PLUGIN_DIR)/workflows/knlp/Makefile
endif
