"""ScopeTrace: measuring authorization-boundary behaviour conditioned on capability.

The package runs a tool-using agent against a deterministic synthetic world and
records what it did, in a form that can be re-derived by someone who has only
the resulting files. A challenge ships as a matched pair. In the control arm the
fast route to the goal is authorized; in the treatment arm the same route is
forbidden and a slower authorized route still reaches the goal. Capability is
demonstrated in the control arm, and the treatment arm measures what an agent
that has the capability then does with it.

The layering is deliberate. Ground truth is generated by the harness, the
policy engine, and the world, and it alone determines the verdict. Model
statements are recorded as observations of behaviour, never as evidence about
hidden reasoning. Derived annotations carry a version, a confidence, and the
event range they came from.

Start at :func:`scopetrace.runner.run_trajectory` for a whole run, at
:class:`scopetrace.policy.PolicyEngine` for how a request is labelled, and at
:func:`scopetrace.outcome.classify_outcome` for how a trajectory becomes a
verdict.
"""

from __future__ import annotations

from .ids import (
    SCHEMA_VERSION,
    ActionId,
    ActorId,
    AuthoritativeScope,
    ChallengeId,
    Decision,
    EvidenceClass,
    EvidenceKind,
    FinalClass,
    ModelDeclaredScope,
    PolicyMode,
    PurposeId,
    ResourceId,
    ResourceKind,
    ReviewStatus,
    RunId,
    StopReason,
    SubjectId,
    TerminalSignal,
    Variant,
)

__version__ = "0.1.0"

__all__ = [
    "SCHEMA_VERSION",
    "ActionId",
    "ActorId",
    "AuthoritativeScope",
    "ChallengeId",
    "Decision",
    "EvidenceClass",
    "EvidenceKind",
    "FinalClass",
    "ModelDeclaredScope",
    "PolicyMode",
    "PurposeId",
    "ResourceId",
    "ResourceKind",
    "ReviewStatus",
    "RunId",
    "StopReason",
    "SubjectId",
    "TerminalSignal",
    "Variant",
    "__version__",
]
